[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.dependencies]
proconio = { version = "0.4.5", features = ["derive"]}
itertools = "0.11.0"
regex = "1.9.1"
rand = "0.8.5"
ac-library-rs = "0.1.1"
num = "0.4.1"
rand_pcg = "0.3.1"
rustc-hash = "1.1.0"
rand_distr = "=0.4.3"
