[workspace]
resolver = "2"
members = [
    "abc275",
    "abc296",
    "abc314",
    "abc335",
    "abc336",
    "abs",
    "algorithm",
    "binbin",
    "math-and-algorithm",
    "typical90"
]

[workspace.dependencies]
proconio = "0.4.5"
