[general]
version = "0.1.1"

[problem]
problem_name = "ahc042"
objective = "Max"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

[[test.compile_steps]]
program = "cargo"
args = [
    "build",
    "--release",
]

[[test.compile_steps]]
program = "rm"
args = [
    "-f",
    "./ahc042",
]

[[test.compile_steps]]
program = "mv"
args = [
    "./target/release/ahc042",
    "./ahc042",
]

[[test.test_steps]]
program = "./ahc042"
args = []
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

[[test.test_steps]]
program = "cargo"
args = [
    "run",
    "--bin",
    "vis",
    "--release",
    "./in/{SEED04}.txt",
    "./out/{SEED04}.txt",
]
current_dir = "./tools"
measure_time = false

